In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder





data = pd.read_csv("C:\\Users\ENOCH\OneDrive\Documents\Project files\corona_tested_individuals_ver_006.english.csv",
                   dtype={'column1': int, 'column2': int, 'column3': int, 'column4': int, 'column5': int})


print("Dataset length::", len(data))
print("Dataset shape::", data.shape)
print(data)



Dataset length:: 278848
Dataset shape:: (278848, 10)
         test_date cough fever sore_throat shortness_of_breath head_ache  \
0       30/04/2020     0     0           0                   0         0   
1       30/04/2020     1     0           0                   0         0   
2       30/04/2020     0     1           0                   0         0   
3       30/04/2020     1     0           0                   0         0   
4       30/04/2020     1     0           0                   0         0   
...            ...   ...   ...         ...                 ...       ...   
278843  11/03/2020     0     0           0                   0         0   
278844  11/03/2020     0     0           0                   0         0   
278845  11/03/2020     0     0           0                   0         0   
278846  11/03/2020     0     0           0                   0         0   
278847  11/03/2020     0     0           0                   0         0   

       corona_result age_60_and_ab

C:\Users\ENOCH\AppData\Local\Temp\ipykernel_15576\4183268176.py:14: DtypeWarning: Columns (1,2,3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("C:\\Users\ENOCH\OneDrive\Documents\Project files\corona_tested_individuals_ver_006.english.csv",


In [9]:
print("Dataset:: ")
data.head()

Dataset:: 


test_date cough fever sore_throat shortness_of_breath head_ache  \
0  30/04/2020     0     0           0                   0         0   
1  30/04/2020     1     0           0                   0         0   
2  30/04/2020     0     1           0                   0         0   
3  30/04/2020     1     0           0                   0         0   
4  30/04/2020     1     0           0                   0         0   

  corona_result age_60_and_above  gender test_indication  
0      negative             None  female           Other  
1      negative             None  female           Other  
2      negative             None    male           Other  
3      negative             None  female           Other  
4      negative             None    male           Other

In [10]:
data.head()

test_date cough fever sore_throat shortness_of_breath head_ache  \
0  30/04/2020     0     0           0                   0         0   
1  30/04/2020     1     0           0                   0         0   
2  30/04/2020     0     1           0                   0         0   
3  30/04/2020     1     0           0                   0         0   
4  30/04/2020     1     0           0                   0         0   

  corona_result age_60_and_above  gender test_indication  
0      negative             None  female           Other  
1      negative             None  female           Other  
2      negative             None    male           Other  
3      negative             None  female           Other  
4      negative             None    male           Other

In [11]:
data.shape

(278848, 10)

In [12]:
data

test_date cough fever sore_throat shortness_of_breath head_ache  \
0       30/04/2020     0     0           0                   0         0   
1       30/04/2020     1     0           0                   0         0   
2       30/04/2020     0     1           0                   0         0   
3       30/04/2020     1     0           0                   0         0   
4       30/04/2020     1     0           0                   0         0   
...            ...   ...   ...         ...                 ...       ...   
278843  11/03/2020     0     0           0                   0         0   
278844  11/03/2020     0     0           0                   0         0   
278845  11/03/2020     0     0           0                   0         0   
278846  11/03/2020     0     0           0                   0         0   
278847  11/03/2020     0     0           0                   0         0   

       corona_result age_60_and_above  gender         test_indication  
0           negative             None  female                   Other  
1           negative             None  female                   Other  
2           negative             None    male                   Other  
3           negative             None  female                   Other  
4           negative             None    male                   Other  
...              ...              ...     ...                     ...  
278843      negative             None    None                   Other  
278844      negative             None    None                   Other  
278845      positive             None    None  Contact with confirmed  
278846         other             None    None                   Other  
278847      negative             None    None                   Other  

[278848 rows x 10 columns]

In [13]:
x =data[['test_date','cough','fever','sore_throat','shortness_of_breath','head_ache','age_60_and_above','gender','test_indication']].values

In [14]:
x

array([['30/04/2020', 0, 0, ..., 'None', 'female', 'Other'],
       ['30/04/2020', 1, 0, ..., 'None', 'female', 'Other'],
       ['30/04/2020', 0, 1, ..., 'None', 'male', 'Other'],
       ...,
       ['11/03/2020', '0', '0', ..., 'None', 'None',
        'Contact with confirmed'],
       ['11/03/2020', '0', '0', ..., 'None', 'None', 'Other'],
       ['11/03/2020', '0', '0', ..., 'None', 'None', 'Other']],
      dtype=object)

In [15]:
y = data[['corona_result']].values

In [16]:
y

array([['negative'],
       ['negative'],
       ['negative'],
       ...,
       ['positive'],
       ['other'],
       ['negative']], dtype=object)

In [18]:
label_encode_x= LabelEncoder()

In [19]:
x[:,0] = label_encode_x.fit_transform(x[:,0])
x

array([[49, 0, 0, ..., 'None', 'female', 'Other'],
       [49, 1, 0, ..., 'None', 'female', 'Other'],
       [49, 0, 1, ..., 'None', 'male', 'Other'],
       ...,
       [10, '0', '0', ..., 'None', 'None', 'Contact with confirmed'],
       [10, '0', '0', ..., 'None', 'None', 'Other'],
       [10, '0', '0', ..., 'None', 'None', 'Other']], dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

label_encode_x= LabelEncoder()

In [22]:
x[:,0]=label_encode_x.fit_transform(x[:,0])
x

array([[49, 0, 0, ..., 'None', 'female', 'Other'],
       [49, 1, 0, ..., 'None', 'female', 'Other'],
       [49, 0, 1, ..., 'None', 'male', 'Other'],
       ...,
       [10, '0', '0', ..., 'None', 'None', 'Contact with confirmed'],
       [10, '0', '0', ..., 'None', 'None', 'Other'],
       [10, '0', '0', ..., 'None', 'None', 'Other']], dtype=object)

In [26]:
onehotencoder= OneHotEncoder()

In [27]:
onehotencoder.fit_transform(data.age_60_and_above.values.reshape(-1, 1)).toarray()

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [28]:
x[:,6]=label_encode_x.fit_transform(x[:,6])
x

array([[49, 0, 0, ..., 1, 'female', 'Other'],
       [49, 1, 0, ..., 1, 'female', 'Other'],
       [49, 0, 1, ..., 1, 'male', 'Other'],
       ...,
       [10, '0', '0', ..., 1, 'None', 'Contact with confirmed'],
       [10, '0', '0', ..., 1, 'None', 'Other'],
       [10, '0', '0', ..., 1, 'None', 'Other']], dtype=object)

In [29]:
onehotencoder=OneHotEncoder()

In [29]:
onehotencoder.fit_transform(data.gender.values.reshape(-1, 1)).toarray()

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [30]:
x[:,7]=label_encode_x.fit_transform(x[:,7])
x

array([[49, 0, 0, ..., 1, 1, 'Other'],
       [49, 1, 0, ..., 1, 1, 'Other'],
       [49, 0, 1, ..., 1, 2, 'Other'],
       ...,
       [10, '0', '0', ..., 1, 0, 'Contact with confirmed'],
       [10, '0', '0', ..., 1, 0, 'Other'],
       [10, '0', '0', ..., 1, 0, 'Other']], dtype=object)

In [31]:
onehotencoder=OneHotEncoder()
onehotencoder.fit_transform(data.test_indication.values.reshape(-1, 1)).toarray()

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [32]:
x[:,8]=label_encode_x.fit_transform(x[:,8])
x

array([[49, 0, 0, ..., 1, 1, 2],
       [49, 1, 0, ..., 1, 1, 2],
       [49, 0, 1, ..., 1, 2, 2],
       ...,
       [10, '0', '0', ..., 1, 0, 1],
       [10, '0', '0', ..., 1, 0, 2],
       [10, '0', '0', ..., 1, 0, 2]], dtype=object)

In [32]:
labelencoder_y=LabelEncoder()

In [33]:
y=labelencoder_y.fit_transform(y[:,0])

In [34]:
y

array([0, 0, 0, ..., 2, 1, 0])

In [35]:
x_column_names = ['test_date','cough','fever','sore_throat','shortness_of_breath','head_ache','age_60_and_above','gender','test_indication']

In [36]:
data_encoded = pd.DataFrame(x, columns=x_column_names)
data_encoded['corona_result']=y

In [37]:
data_encoded.to_csv('CoronaVirus_Dataset.csv', index=False)

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278848 entries, 0 to 278847
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   test_date            278848 non-null  object
 1   cough                278848 non-null  object
 2   fever                278848 non-null  object
 3   sore_throat          278848 non-null  object
 4   shortness_of_breath  278848 non-null  object
 5   head_ache            278848 non-null  object
 6   corona_result        278848 non-null  object
 7   age_60_and_above     278848 non-null  object
 8   gender               278848 non-null  object
 9   test_indication      278848 non-null  object
dtypes: object(10)
memory usage: 21.3+ MB


In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278848 entries, 0 to 278847
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   test_date            278848 non-null  object
 1   cough                278848 non-null  object
 2   fever                278848 non-null  object
 3   sore_throat          278848 non-null  object
 4   shortness_of_breath  278848 non-null  object
 5   head_ache            278848 non-null  object
 6   corona_result        278848 non-null  object
 7   age_60_and_above     278848 non-null  object
 8   gender               278848 non-null  object
 9   test_indication      278848 non-null  object
dtypes: object(10)
memory usage: 21.3+ MB


In [ ]:
from sklearn.model_selection import train_test_split

In [40]:
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size = 0.2, random_state =0)

In [41]:
x_train

array([[29, 1, 0, ..., 1, 'male', 'Other'],
       [21, 0, 0, ..., 1, 'female', 'Other'],
       [25, 0, 0, ..., 1, 'male', 'Other'],
       ...,
       [19, 0, 0, ..., 1, 'female', 'Other'],
       [9, '0', '0', ..., 0, 'male', 'Other'],
       [19, 0, 0, ..., 1, 'male', 'Other']], dtype=object)

In [42]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [46]:
x_test

array([[46, '0', '0', ..., 0, 'female', 'Other'],
       [3, '0', '0', ..., 0, 'female', 'Other'],
       [48, '0', '0', ..., 0, 'male', 'Other'],
       ...,
       [4, '0', '0', ..., 0, 'female', 'Other'],
       [46, '0', '0', ..., 2, 'female', 'Other'],
       [34, '0', '0', ..., 0, 'male', 'Other']], dtype=object)

In [48]:
from sklearn.preprocessing import StandardScaler

In [49]:
sc_x= StandardScaler()

In [50]:
x_train=sc_x.fit_transform(x_train)

ValueError: could not convert string to float: 'male'